services:
  - type: web
    name: chatbot
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn chatbot_project.wsgi:application --bind 0.0.0.0:8000
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DJANGO_SETTINGS_MODULE
        value: chatbot_project.settings
      - key: PORT
        value: 8000
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: False
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3